eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  tomcat:
    accesslog:
      enabled: true
  port: 8774
spring:
  application:
    name: email-service

logging:
  file:
    name: vault/logs/catalina-email.out

  level:
    org:
      apache:
        catalina: INFO
        tomcat: INFO

